services:
  bepusdt:
    build: .  # 使用本地代码构建
    image: bepusdt:local  # 本地构建的镜像标签
    container_name: bepusdt 
    restart: unless-stopped 
    ports: 
      - "8080:8080" 
    volumes: 
      - ./conf.toml:/usr/local/bepusdt/conf.toml
      - ./data:/var/lib/bepusdt
